"""empty message

Revision ID: 10f7f80917d2
Revises: a220a5cba86e
Create Date: 2024-03-13 19:56:41.149011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f7f80917d2'
down_revision: Union[str, None] = 'a220a5cba86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralToken', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('referralToken', 'ttl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralToken', sa.Column('ttl', postgresql.INTERVAL(), autoincrement=False, nullable=False))
    op.drop_column('referralToken', 'expires_at')
    # ### end Alembic commands ###
