"""empty message

Revision ID: 43bc51ea577b
Revises: e5bf914a35a3
Create Date: 2024-03-12 23:53:35.007824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bc51ea577b'
down_revision: Union[str, None] = 'e5bf914a35a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
