"""empty message

Revision ID: 4da9a6b3a715
Revises: e0432e6aa7ef
Create Date: 2024-03-14 17:45:42.495460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da9a6b3a715'
down_revision: Union[str, None] = 'e0432e6aa7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('referralToken_owner_id_fkey', 'referralToken', type_='foreignkey')
    op.create_foreign_key(None, 'referralToken', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referralToken', type_='foreignkey')
    op.create_foreign_key('referralToken_owner_id_fkey', 'referralToken', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
