"""empty message

Revision ID: 55d279868d6b
Revises: 4da9a6b3a715
Create Date: 2024-03-14 17:47:20.464976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d279868d6b'
down_revision: Union[str, None] = '4da9a6b3a715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_redeemed_token_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'referralToken', ['redeemed_token_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_redeemed_token_id_fkey', 'user', 'referralToken', ['redeemed_token_id'], ['id'])
    # ### end Alembic commands ###
