"""empty message

Revision ID: 74713f14a781
Revises: 77d8178e1a7f
Create Date: 2024-03-13 19:28:28.981438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74713f14a781'
down_revision: Union[str, None] = '77d8178e1a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'referralToken', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referralToken', type_='unique')
    # ### end Alembic commands ###
