"""empty message

Revision ID: 759135fe157a
Revises: 2fd179894ff4
Create Date: 2024-03-13 19:47:49.464078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759135fe157a'
down_revision: Union[str, None] = '2fd179894ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralToken', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referralToken', 'expires_at')
    # ### end Alembic commands ###
