"""empty message

Revision ID: 77d8178e1a7f
Revises: da4f320e3525
Create Date: 2024-03-13 19:20:16.864213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d8178e1a7f'
down_revision: Union[str, None] = 'da4f320e3525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralToken', sa.Column('token_name', sa.String(length=100), nullable=False))
    op.drop_constraint('referralToken_token_key', 'referralToken', type_='unique')
    op.create_unique_constraint(None, 'referralToken', ['token_name'])
    op.drop_column('referralToken', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referralToken', sa.Column('token', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referralToken', type_='unique')
    op.create_unique_constraint('referralToken_token_key', 'referralToken', ['token'])
    op.drop_column('referralToken', 'token_name')
    # ### end Alembic commands ###
