"""empty message

Revision ID: e5bf914a35a3
Revises: ebb8c53e44f6
Create Date: 2024-03-12 23:40:11.272142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bf914a35a3'
down_revision: Union[str, None] = 'ebb8c53e44f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referralToken',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('ttl', sa.Interval(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('user', sa.Column('redeemed_token_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'referralToken', ['redeemed_token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'redeemed_token_id')
    op.drop_table('referralToken')
    # ### end Alembic commands ###
