version: '3.8'

services:
  postgres:
    container_name: referral_postgres
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: "web_app"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "web_app", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 12
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    container_name: referral_redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 10
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: referral_app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
