version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: referral_redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: referral_app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0, --port 8001"
    ports:
      - 8001:8001

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:

